### ISSUE TITLE
Delete method of ThumbnailerFieldFile is called twice 

### ISSUE THREAD

**Issue by shmel210** [SmileyChris/easy-thumbnails#456]
How to reproduce: install and enable.
`
Django==1.11
django-cleanup==0.4.2
django-modeltranslation==0.12.1

class TaskAnswer(models.Model):
    task = models.ForeignKey(Task, verbose_name=_('task'))
    title = models.CharField(_('title'), max_length=255, blank=True)
    audio = AudioField(_('audio'), upload_to='uploads/%Y/%m/%d/', blank=True)
    image = ThumbnailerImageField(verbose_name=_('image'), upload_to='uploads/%Y/%m/%d/',
                                  resize_source={'size': (2000, 2000), 'sharpen': True, 'quality': 100}, blank=True)
    is_correct = models.BooleanField(verbose_name=_('is answer correct'), default=False, blank=True)

    def __unicode__(self):
        return self.title or str(self.pk)

    class Meta:
        verbose_name = _('answer')
        verbose_name_plural = _('answers')
        ordering = ['-id']

class AnswerAdminInline(TranslationTabularInline):
    # form = AnswerAdminForm
    model = TaskAnswer
    extra = 1

@register(TaskAnswer)
class AnswerTranslationOptions(TranslationOptions):
    fields = ('title', 'audio', 'image')
`
Add new answer and  than try to delete it.

Traceback
`
RROR: [time:2017-04-14 11:13:51,066] [module:exception] [pid:20914] [thread:139849461159680] Internal Server Error: /en/admin/schools/task/1/change/
Traceback (most recent call last):
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1511, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 267, in __exit__
    connection.set_autocommit(True)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 416, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
    func()
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django_cleanup/handlers.py", line 92, in run_on_commit
    file_.delete(save=False)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 386, in delete:
   super(ImageFieldFile, self).delete(save)
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 684, in delete
    source_cache.delete()
  File "/home/shmel/projects/rozumaka.com.ua/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 967, in delete
    (self._meta.object_name, self._meta.pk.attname)
AssertionError: Source object can't be deleted because its id attribute is set to None.
ERROR: [time:2017-04-14 11:13:54,994] [module:basehttp] [pid:20914] [thread:139849461159680] "POST /en/admin/schools/task/1/change/ HTTP/1.1" 500 21047
`

I added pk check as fast fix.
`    def delete(self, *args, **kwargs):
        """
        Delete the image, along with any generated thumbnails.
        """
        source_cache = self.get_source_cache()
        # First, delete any related thumbnails.
        self.delete_thumbnails(source_cache)
        # Next, delete the source image.
        super(ThumbnailerFieldFile, self).delete(*args, **kwargs)
        # Finally, delete the source cache entry.
        if source_cache and source_cache.pk is not None:
            source_cache.delete()`

**Comment by aibear** [comment]
"I think you're probably using the admin's bulk delete feature, and are running into the fact that the admin's bulk delete method doesn't call delete() "
if i were right, you should probably to check [http://stackoverflow.com/questions/1471909/django-model-delete-not-triggered](this),
he had provided a good solution.

**Comment by aibear** [comment]
if you  want to  Delete the image, along with any generated thumbnails. ,you can try this:
(put this in your TaskAnswer model)
` def delete(self, *args, **kwargs):
        """delete -- Remove images."""
        self.image.delete()
        super(TaskAnswer, self).delete(*args, **kwargs)
`
