### ISSUE TITLE
Compatibility with Django 1.11

### ISSUE THREAD

**Issue by yusufkaracin** [SmileyChris/easy-thumbnails#459]
When I try to run with Django 1.11:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe563a5c840>
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/ubuntu/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ubuntu/venv/lib/python3.5/site-packages/easy_thumbnails/models.py", line 6, in <module>
    from easy_thumbnails import utils, signal_handlers
  File "/home/ubuntu/venv/lib/python3.5/site-packages/easy_thumbnails/utils.py", line 15, in <module>
    from easy_thumbnails.conf import settings
  File "/home/ubuntu/venv/lib/python3.5/site-packages/easy_thumbnails/conf.py", line 334, in <module>
    settings = Settings()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/easy_thumbnails/conf.py", line 21, in __init__
    super(AppSettings, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'settings_module'
```

**Comment by jrief** [comment]
You are welcomed to fix this and create a pull request.
We are all very busy to handle this ourselves.

**Comment by claudep** [comment]
You are probably not running the latest release.

**Comment by yusufkaracin** [comment]
thanks @claudep
