### ISSUE TITLE
Looks like a bug or version incompatibility in easy_thumbnail. It calls the base class without the required argument settings_module

### ISSUE THREAD

**Issue by NhaTrang** [SmileyChris/easy-thumbnails#460]
`Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python35\lib\site-packages\django\core\management\commands\runserver.
py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python35\lib\site-packages\django\utils\autoreload.py", line 250, in
raise_last_exception
    six.reraise(*_exception)
  File "C:\Python35\lib\site-packages\django\utils\six.py", line 685, in reraise

    raise value.with_traceback(tb)
  File "C:\Python35\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python35\lib\site-packages\django\apps\registry.py", line 108, in pop
ulate
    app_config.import_models()
  File "C:\Python35\lib\site-packages\django\apps\config.py", line 202, in impor
t_models
    self.models_module = import_module(models_module_name)
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\mysite\calendarium\models.py", line 14, in <module>
    from filer.fields.image import FilerImageField
  File "C:\Python35\lib\site-packages\filer\fields\image.py", line 4, in <module
>
    from ..models import Image
  File "C:\Python35\lib\site-packages\filer\models\__init__.py", line 3, in <mod
ule>
    from .clipboardmodels import *  # flake8: noqa
  File "C:\Python35\lib\site-packages\filer\models\clipboardmodels.py", line 9,
in <module>
    from . import filemodels
  File "C:\Python35\lib\site-packages\filer\models\filemodels.py", line 18, in <
module>
    from ..fields.multistorage_file import MultiStorageFileField
  File "C:\Python35\lib\site-packages\filer\fields\multistorage_file.py", line 1
2, in <module>
    from easy_thumbnails import fields as easy_thumbnails_fields
  File "C:\Python35\lib\site-packages\easy_thumbnails\fields.py", line 2, in <mo
dule>
    from easy_thumbnails import files
  File "C:\Python35\lib\site-packages\easy_thumbnails\files.py", line 14, in <mo
dule>
    from easy_thumbnails import engine, exceptions, models, utils, signals, stor
age
  File "C:\Python35\lib\site-packages\easy_thumbnails\engine.py", line 12, in <m
odule>
    from easy_thumbnails import utils
  File "C:\Python35\lib\site-packages\easy_thumbnails\utils.py", line 15, in <mo
dule>
    from easy_thumbnails.conf import settings
  File "C:\Python35\lib\site-packages\easy_thumbnails\conf.py", line 334, in <mo
dule>
    settings = Settings()
  File "C:\Python35\lib\site-packages\easy_thumbnails\conf.py", line 21, in __in
it__
    super(AppSettings, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'settings_module'`

**Comment by jrief** [comment]
please learn how to issue proper error reports.
