### ISSUE TITLE
Can't use callable default in `ImageField` with easy thumbnails?

### ISSUE THREAD

**Issue by mrmachine** [SmileyChris/easy-thumbnails#468]
I'm trying to use a callable as `default` for an image field. This callable returns a string (the name to an image for the configured storage class). This works when I create an object in a Python interactive shell, but breaks when I create an object via the Django admin:

```
Traceback (most recent call last):
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/core/handlers/base.py", line 229, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/adminsortable/admin.py", line 178, in add_view
    extra_context=extra_context)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1164, in add_view
    self.save_model(request, new_object, form, False)
  File "/Users/tailee/IC/Projects/syrinscape/djangosite/syrinscape/admin.py", line 48, in save_model
    obj.save()
  File "/Users/tailee/IC/Projects/syrinscape/djangosite/syrinscape/models.py", line 518, in save
    result = super(Chapter, self).save(*args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/adminsortable/models.py", line 66, in save
    super(Sortable, self).save(*args, **kwargs)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/db/models/base.py", line 569, in save_base
    update_fields=update_fields)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/tailee/.pyenv/versions/2.7.13/envs/syrinscape-prod/src/easy-thumbnails/easy_thumbnails/signal_handlers.py", line 16, in find_uncommitted_filefields
    if not getattr(instance, field.name)._committed:
AttributeError: 'function' object has no attribute '_committed'
```

It seems the `find_uncommitted_filefields` signal handler is being passed an object whose image file field is still the callable that returns a default, instead of being a `FieldFile`.

**Comment by mrmachine** [comment]
Nevermind. This is a Django bug. See: https://code.djangoproject.com/ticket/24823
