### ISSUE TITLE
Python 3.6 PIL error

### ISSUE THREAD

**Issue by MerlinB** [SmileyChris/easy-thumbnails#488]
I recently upgraded from Python 3.5 to 3.6.3, as a result Django threw this error:
 ```
Traceback (most recent call last):
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/easy_thumbnails/engine.py", line 8, in <module>
    from PIL import Image
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scholarium/scholarium_staging/seite/local_wsgi.py", line 17, in <module>
    application = get_wsgi_application()
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/scholarium/scholarium_staging/venv/lib/python5.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/scholarium/scholarium_staging/Grundgeruest/models.py", line 14, in <module>
    from userena.models import UserenaBaseProfile, UserenaSignup
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/userena/models.py", line 9, in <module>
    from easy_thumbnails.fields import ThumbnailerImageField
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/easy_thumbnails/fields.py", line 2, in <module>
    from easy_thumbnails import files
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/easy_thumbnails/files.py", line 14, in <module>
    from easy_thumbnails import engine, exceptions, models, utils, signals, storage
  File "/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages/easy_thumbnails/engine.py", line 10, in <module>
    import Image
ImportError: No module named 'Image'
```
Relevant versions are:
```
easy-thumbnails==2.5 (no change at 2.4.2)
Django==1.11.6
Pillow==4.3.0 (irrelevant?)
```
It seems to be related to the outdated PIL library?

**Comment by jrief** [comment]
I have no problems with Python-3.6. However, I'm using Pillow-3.3.0
Let's retry and report.

**Comment by MerlinB** [comment]
No changes with Pillow-3.3.0.

**Comment by jrief** [comment]
PIL/Pillow have C code which has to be compiled. Presumably there are some problems during the installation. Please check their docs on how to fix this.
I'm closing this issue, because it is unrelated to easy-thumbnails.
